spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: Priti@05

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka